jobs:
  - script: folder('example-team-1')
  - script: >
      pipelineJob('example') {
          definition {
              cpsScm {
                  scm {
                      git('https://github.com/jenkinsci/job-dsl-plugin.git')
                  }
              }
          }
      }
  - script: >
      pipelineJob('example-team-1/example-workload-D-test') {
        definition {
          cpsScm {
            scm {
              scriptPath('workloads/example-team-1/example-workload-D/workload-test.groovy')
            }
          }
        }
      }

  - script: folder('example-team-2')
  - script: >
      pipelineJob('example-team-2/example-workload-B-test') {
        definition {
          cpsScm {
            scm {
              scriptPath('workloads/example-team-2/example-workload-B/workload-test.groovy')
            }
          }
        }
      }
  - script: >
      pipelineJob('example-team-2/example-workload-C-test') {
        definition {
          cpsScm {
            scm {
              scriptPath('workloads/example-team-2/example-workload-C/workload-test.groovy')
            }
          }
        }
      }
  - script: >
      pipelineJob('SOAK Workloads') {
        definition {
          cpsScm {
            scm {
              scriptPath('workloads/Jenkinsfile')
            }
          }
        }
      }
