jobs:
  - script: folder('example-team-1')
  - script: >
      pipelineJob('example-team-1/example-workload-A-test') {
        definition {
          cpsScm {
            scm {
              github('janisz/dcos', 'workloads_tests')
              scriptPath('workloads/example-team-1/example-workload-A/workload-test.groovy')
            }
          }
        }
      }
  - script: >
      pipelineJob('example-team-1/example-workload-D-test') {
        definition {
          cpsScm {
            scm {
              github('janisz/dcos', 'workloads_tests')
              scriptPath('workloads/example-team-1/example-workload-D/workload-test.groovy')
            }
          }
        }
      }

  - script: folder('example-team-2')
  - script: >
      pipelineJob('example-team-2/example-workload-B-test') {
        definition {
          cpsScm {
            scm {
              github('janisz/dcos', 'workloads_tests')
              scriptPath('workloads/example-team-2/example-workload-B/workload-test.groovy')
            }
          }
        }
      }
  - script: >
      pipelineJob('example-team-2/example-workload-C-test') {
        definition {
          cpsScm {
            scm {
              github('janisz/dcos', 'workloads_tests')
              scriptPath('workloads/example-team-2/example-workload-C/workload-test.groovy')
            }
          }
        }
      }
  - script: >
      pipelineJob('SOAK Workloads') {
        definition {
          cpsScm {
            scm {
              github('janisz/dcos', 'workloads_tests')
              scriptPath('workloads/Jenkinsfile')
            }
          }
        }
        triggers {
            cron('*/5 * * * *')
            githubPush()
        }
      }
unclassified:
  gitscm:
    globalConfigName: jenkins
    globalConfigEmail: jenkins@soak
    createAccountBasedOnEmail: true
